# Generated by Django 5.0.6 on 2024-05-28 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_remove_product_digital_remove_product_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Product',
            new_name='product',
        ),
    ]
