# Generated by Django 5.0.6 on 2024-05-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshopcare', '0002_bodysoap_pub_date_facecleanser_pub_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facecleanser',
            old_name='volume',
            new_name='weight',
        ),
        migrations.RenameField(
            model_name='liquidsoap',
            old_name='volume',
            new_name='weight',
        ),
        migrations.RenameField(
            model_name='oil',
            old_name='volume',
            new_name='weight',
        ),
        migrations.RenameField(
            model_name='scrub',
            old_name='volume',
            new_name='weight',
        ),
        migrations.RenameField(
            model_name='shampoo',
            old_name='volume',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='bodysoap',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='bodysoap',
            name='scent',
        ),
        migrations.RemoveField(
            model_name='bodysoap',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='facecleanser',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='facecleanser',
            name='scent',
        ),
        migrations.RemoveField(
            model_name='liquidsoap',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='liquidsoap',
            name='scent',
        ),
        migrations.RemoveField(
            model_name='oil',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='oil',
            name='scent',
        ),
        migrations.RemoveField(
            model_name='scrub',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='scrub',
            name='scent',
        ),
        migrations.RemoveField(
            model_name='shampoo',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='shampoo',
            name='scent',
        ),
        migrations.AlterField(
            model_name='bodysoap',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
