# Generated by Django 5.0.6 on 2024-05-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshopcare', '0003_rename_volume_facecleanser_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodysoap',
            name='image',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='facecleanser',
            name='image',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='liquidsoap',
            name='image',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='oil',
            name='image',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='scrub',
            name='image',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='shampoo',
            name='image',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
